# Generated by Django 3.1.5 on 2021-01-27 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choice',
            new_name='Escolhas',
        ),
    ]
